lib/Bugsnag.js
Here are two small changes to make it easier to report promise rejections to Bugsnag.
1. Replace client functions with fat arrows to ensure they are bound ahead of time. This makes it easier to call `client.notify` as a part of a rejection handler.
2. Add a configuration option, `handlePromiseRejections` which enables catching and reporting any unhandled promise rejection. By default, it is only enabled in release mode, to ensure the banner is presented during development.
Fixes #9
=> Handle promise rejections

lib/Bugsnag.js
Loading bugsnag currently breaks the default redbox behavior in development. This is because the react native `ErrorUtils` has been changed. The `_globalHandler` member is now private and has been replaced with a [proper getter](https://github.com/facebook/react-native/blob/3137ba993dbc3645832283ab683d18950c4246ed/packager/react-packager/src/Resolver/polyfills/error-guard.js#L33-L35).
=> Fix default redbox error handling in development

android/src/main/java/com/bugsnag/BugsnagReactNative.java
Fixes https://github.com/bugsnag/bugsnag-react-native/issues/32 (see issue for details).
The case statement I added is similar to the one lower down in `DiagnosticsCallback#readObjectMap`. It seems like it would be better to use [`ReadableMap#getType`](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableMap.java#L26) and switch on [`ReadableType`](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableType.java), but I didn't want to change that logic in this PR.
This will probably cause merge conflicts with https://github.com/bugsnag/bugsnag-react-native/pull/29 due to changes in the example app. I'll happily rebase on that PR if that's easier.
Test with the Android …
=> Fix breadcrumb crash

cocoa/BugsnagReactNative.h, cocoa/BugsnagReactNative.m
As you can see from [RN 0.40 release notes](https://github.com/facebook/react-native/releases/tag/v0.40.0) they have moved ALL native modules on iOS. All packages that use `.h`-files starting with `RCT` they have to be refactored to the new path.
So basically `bugsnag-react-native` won't work with RN 0.40 without this PR! :)
=> Update iOS header imports for RN 0.40

.gitignore, lib/Bugsnag.js
This PR makes the code follow more standard JS conventions, fixing several major bugs related to breadcrumb logging. It also tackles a few other cleanup items related to the changes.
1. Properly log objects, booleans, `null`, and `undefined` in breadcrumbs
- Previously, **all of these values were completely dropped without warning**
1. Use `typeof` in several places instead of various alternatives
- See [here](http://stackoverflow.com/questions/899574/which-is-best-to-use-typeof-or-instanceof) for more info
- Fixes a few potential bugs with inheritance and prototype modification
1. ~~Use regular functions instead of closures~~ (previously 22aac3a)
1. Check `hasOwnProperty` before adding to typedMap output
1. Output slightly more helpful warnings
1. Ignore the `.idea` directory created by …
=> Conventionalize to fix sneaky breadcrumb logging bugs

lib/Bugsnag.js
The `codeBundleId` property is proposed as an alternative to `appVersion` which can be updated every time a new deployment is published, such as by using CodePush. The number would need to be updated before each `release-react` or similar, and match a `codeBundleId` sent with source map uploads.
Related: #35
=> Allow setting codeBundleId as a config option

lib/Bugsnag.js
Added a check for shouldNotify before notifying Bugsnag of any uncaught error. This error was found using releaseStages, and running the app with a releaseStage that should not notify. Since it should not notify, the callback was never called. And with that, the previousHandler was never called.
=> fix: send uncaught errors to the original error handler when one should not notify Bugsnag

lib/Bugsnag.js
Anecdotally, it appears that breadcrumb names get truncated at 30 characters. I didn't see this specifically mentioned in the docs, but a few of my events were truncated online so it seems like it would be good to have a warning for this.
=> Add warning when breadcrumb name exceeds max length

src/Bugsnag.js
You should not remove the type property of metadata. It will mutate the original object and can cause some issues in the project which uses this module. It's better to create a new Object and remove the type property there.
=> Don't remove type property with mutation

BugsnagReactNative.podspec
This works around an issue (that's possibly with CocoaPods) in the podfile where, when installed via CocoaPods, many header files were not marked as public in the target framework.
=> Ensure header files are marked as public when installed via CocoaPods

package.json
The npm registry and client use these fields to direct people to the appropriate places to find out more about a package.
I always have to hunt for the repository when a new version is released so that I can find the CHANGELOG. 😄 
Have a great day!
=> Add homepage, repository, and bugs to package.json

src/Bugsnag.js
Nested objects are being prematurely stringified when attached as metadata. This patch refines the NaN check in f847a7390fe3683c0723280de18c169715017ccc to ensure it is only applied to numbers.
Fixes #132
=> Fix nested object serialization in metadata

BugsnagReactNative.podspec
Since KSCrash has been moved inside cocoa/vendor/bugsnag-cocoa/Source include all sub directories
=> Recursively add all vendor source files

examples/plain/app/components/scenes/main.js, examples/plain/app/components/scenes/register.js, package.json, test-harness/app/components/scenes/main.js, test-harness/app/components/scenes/register.js
See https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes
Also seems to be breaking on react@16.0.0-beta.5 and react-native@0.49.3
=> Replace PropTypes from React with form prop-types package

src/Bugsnag.js, src/__tests__/Bugsnag.test.js
While the console breadcrumbs are great in concept, they've actually led to more crashes in our app than they've helped to diagnose. This PR resolves the underlying issue and adds safeguards to prevent other undiagnosed issues from crashing people's apps.
**The underlying issue**
If a `console.log` statement receives `null` or `undefined` as an argument, the code will throw a `TypeError` because you cannot call `toString()` on these values. In all cases, it's safer to use the `String` constructor than to call `toString()` on a value. (The former will ultimately delegate to `toString()` if defined, but will gracefully handle primitives like `null` and `undefined`.)
**The safeguard**
As new features are added to the tracker, it's important to wrap them in a top-most `try/catch`. We all make …
=> Make console breadcrumbs safe to use

src/Bugsnag.js
Improve validation of handled state to address 2 scenarios:
1) if the `notify` method was passed an object as its 5th parameter, `handledState` would not be created
2) if the `report._handledState` was modified in a `beforeSendCallback`, the `severityReason` could potentially be invalid
=> Improve handled state validation

CONTRIBUTING.md, index.d.ts
Updates TypeScript definitions as types have changed since the [last edit](https://github.com/bugsnag/bugsnag-react-native/compare/v2.7.0...master). Also adds a note to the Contributing instructions to prevent this in future
=> Update typescript defs

src/Bugsnag.js
Hi,
After upgrading to React Native 0.53 we got a warning about `One of the sources for assign has an enumerable key on the prototype chain` when trying to leave breadcrumbs.
Tracking down the issue to the line that throws the exception, this turned out to be the culprit:
```
let type = metadata['type'] || 'manual';
const breadcrumbMetaData = { ...metadata };
delete breadcrumbMetaData['type'];
```
This snippet basically extracts the `type` from the `metadata` and then creates a new object `breadcrumbMetaData` that contains all `metadata` except for the `type`.
In this PR I've reworked the code so that it leverages the ES2015 syntax by destructuring the object and rest spreading all that's left into the new `breadcrumbMetaData` object.
```
const {
type = 'manual',
...breadcrumbMetaData
} = …
```
=> Rework construction of `breadcrumbMetaData`

package.json, src/NativeSerializer.js, src/__tests__/NativeSerializer.test.js, yarn.lock
Fixes #239, extracting the stack and message from a given `Error` class before serialising it.
Error objects do not have an iterator therefore are ignored by the `for` loop.  My initial thoughts were to add an iterator using `Object.keys` to extract all properties into a map, but the Error object does not respond to this either.
Added non-exported method `extractErrorDetails` to `NativeSerializer` that takes an error and returns an object with the Errors `message` and `stack` properties.
Added a unit test to `NativeSerializer.test`
Fixes #239 
For the submitter, initial self-review:
- This pull request is ready for:
For the pull request reviewer(s), this changeset has been reviewed for:
=> fix(Errors): Enable nativeSerializer to handle Error objects

android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties
Making it compatible with react-native 0.56.0
Can use
ext {
buildToolsVersion = "23.0.1"
minSdkVersion = 16
compileSdkVersion = 23
targetSdkVersion = 23
supportLibVersion = "23.0.1"
}
if you are using older tools.
=> Upgrade SDK Build Tools for react-native 0.56.0

index.d.ts
`apiKeyOrConfig === undefined` is being handled at https://github.com/bugsnag/bugsnag-react-native/blob/master/src/Bugsnag.js#L21
=> [Typings] Allow undefined apiKeyOrConfig

.travis.yml, package-lock.json
Fix CI on master, which has started failing due to a change in the Travis image.
The installed node versions differ between the [passing build on v2.12.6](https://travis-ci.com/bugsnag/bugsnag-react-native/jobs/164046377), and the [first build which failed](https://travis-ci.com/bugsnag/bugsnag-react-native/jobs/164046377). Previously we did not specify an exact version of node, which appears to have failed the first job when Travis updated their Javascript image.
- The exact version of node (latest stable) has been specified, and the language changed to node_js, as recommended in [the docs](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions).
- `sudo` is [no longer required](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migra …
=> Fix CI by using node_js language and specifying exact version number

android/build.gradle, android/proguard-rules.pro
Any exception of the type `com.facebook.react.common.JavascriptException` should be ignored by the notifier. This is because any unhandled JS error is captured in both the Android + JS layers. As the JS error contains more relevant information, the Android exception is discarded to avoid duplicates.
If ProGuard is enabled, the class name used to [filter exceptions](https://github.com/bugsnag/bugsnag-react-native/blob/master/android/src/main/java/com/bugsnag/BugsnagReactNative.java#L213)  will be obfuscated, and therefore two errors will be sent for every unhandled JS error triggered.
Adding a keep rule to the consumer proguard file for the library will cause this class name to be retained if obfuscation is enabled.
Sent an unhandled JS exception in the example app with the local artefact …
=> Add proguard consumer rules to retain JavascriptException class

examples/codepush/android/build.gradle, examples/plain/android/build.gradle, features/fixtures/sampler/android/build.gradle, test-harness/android/build.gradle
Specifying `mavenCentral` as a repository in addition to `jcenter` makes it possible to perform a clean build of the project in the case where one provider suffers downtime.
=> Specify maven central as a preferred repository over jcenter

.travis.yml, CHANGELOG.md, android/build.gradle, android/config/checkstyle/checkstyle.xml, android/lint-baseline.xml, android/src/main/java/com/bugsnag/BugsnagPackage.java, android/src/main/java/com/bugsnag/BugsnagReactNative.java, android/src/main/java/com/bugsnag/DiagnosticsCallback.java, android/src/main/java/com/bugsnag/JavaScriptException.java, examples/plain/android/app/build.gradle, examples/plain/android/app/lint-baseline.xml, examples/plain/android/app/src/main/java/com/bugsnagreactnativeexample/CrashyModule.java, examples/plain/android/app/src/main/java/com/bugsnagreactnativeexample/CrashyPackage.java, examples/plain/android/app/src/main/java/com/bugsnagreactnativeexample/MainApplication.java, examples/plain/android/config/checkstyle/checkstyle.xml, examples/plain/android/config/checkstyle/suppressions.xml
Code in bugsnag-react-native did not run checkstyle or Android Lint automatically, which would have helped detect code smells and generally improve code quality. Running these tools on CI should catch issues early and prevent us from shipping violations.
- Setup Android Lint to abort the build on any errors not included within a baseline of ignored issues, in the example project and Android code
- Setup Checkstyle to abort the build on any style errors in the example project and Android code
- Pre-existing violations were also addressed, including:
- Splitting top-level classes into separate files
- Using an indent of 4 rather than 2
- Adding missing braces to conditionals
- Adding default branch to switch statements
- Ordering imports
- Adding missing override modifiers
- Fixing modifier …
=> Run checkstyle and lint on Android code, address existing violations

.travis.yml
Fixes Travis CI failing when the image updated to Xenial, by pinning to Trusty.
The changeset also removes unused env vars, and has replaced manual installation of npm with `nvm` instead.
=> ci: attempt fixing ci by removing unused env vars and system image

examples/plain/android/app/build.gradle, examples/plain/android/app/lint-baseline.xml, examples/plain/android/app/src/main/AndroidManifest.xml, examples/plain/android/build.gradle, examples/plain/android/gradle/wrapper/gradle-wrapper.properties, examples/plain/ios/BugsnagReactNativeExample.xcodeproj/project.pbxproj, examples/plain/package.json, examples/plain/yarn.lock, package-lock.json
Updates the example app to use the latest version of React Native, 0.59.8. The example app was using 0.57.4, which would fail to [boot an iOS simulator](https://github.com/facebook/react-native/issues/23282) with XCode 10.2.
- Updated RN to 0.59.8 and React to 16.8.3
- Ran `react-native upgrade` to perform automatic upgrades
- Linked `JavaScriptCore.framework` in iOS project, as this is now required to build
- Updated gradlew to 4.10.2 (required by latest React Native)
- Updated Android deps to target latest version of Android
- Address some existing lint failures in Android project
Ran the example app on both iOS and Android in release mode and confirmed that an error can be sent to the bugsnag dashboard.
=> Update example app to React Native 0.59.8

CHANGELOG.md, android/src/main/java/com/bugsnag/DiagnosticsCallback.java, android/src/main/java/com/bugsnag/JavaScriptException.java
Google recently migrated the Android support library into the Androidx namespace. When `enableJetifier` is set to true in a project, the binaries are rewritten to use the new package; however, this does not appear to apply to bugsnag-react-native, resulting in compilation failure as the `android.support.annotation` package does not exist.
Addresses #322 and #327 
As our use of the nullability annotations is of limited value, the imports and annotations were removed from the codebase.
Ran in an example app with the following values set:
```
android.useAndroidX=true
android.enableJetifier=true
```
=> Remove nullability annotations to workaround androidx jetifier issue

.travis.yml, cocoa/BugsnagReactNative.m
Read version from macro when available otherwise use newer function
- `pod install` for example
Manual test - Xcode build example project with 
`React (0.49.5)`
`WEAK_IMPORT_ATTRIBUTE` did not work for linking `RCTGetReactNativeVersion()`
Fixes # https://github.com/bugsnag/bugsnag-react-native/issues/371
- This pull request is ready for:
=> get react native version using macro

CHANGELOG.md, android/build.gradle, android/src/main/java/com/bugsnag/BugsnagReactNative.java, android/src/main/java/com/bugsnag/JavaScriptException.java
As part of https://github.com/bugsnag/bugsnag-android/pull/553 the way exceptions are serialised in bugsnag-android was altered. This was to allow the exception name/message to be altered after a `BugsnagException` object has been constructed.
As part of this change, the exception serialisation was altered so that when building an error, all `Throwable` objects must be wrapped in a `BugsnagException` if they are [not already of that type](https://github.com/bugsnag/bugsnag-android/pull/553/files#diff-04f6e695a46ee00c79f74a90c284bb41R59). This meant that `JavaScriptException#toStream()` was not invoked when serialising an error report, leading to the name being serialised as `com.bugsnag.JavaScriptException`, rather than the name of the JS error.
This changeset alters `JavaScriptException` …
=> fix: make JavaScriptException inherit from BugsnagException

CHANGELOG.md, android/src/main/java/com/bugsnag/BugsnagReactNative.java
The version supplied by getSpecificationVersion() always returns 0. We should use the version
supplied by Notifier.getInstance() instead, as we know it will always be accurate, and will allow us to determine which version of bugsnag-android is actually being used for each event.
Confirmed that in a local artefact the message now states:
>Initialized Bugsnag React Native 2.23.2/Android 4.19.1
rather than "0.0".
We want to update the format of our payload to include the RN/Android version separately. This change requires pipeline alterations so is not addressed in this PR.
=> Use the correct android version in Notifier payload

.gitignore, .travis.yml, test/test-react-native-link-build.sh, test/test-react-native-pod-build.sh
This change updates the CI build strategy to create new React Native projects for RN 0.59 and RN 0.61 and check that a linked project compiles. This removes an existing test which added the bugsnag-react-native package to an existing 0.53 project. This change should ensure newer and older versions of RN build correctly with bugsnag-react-native and that issues like #433 are caught automatically.
~This is a draft awaiting #441 being merged, which will make the build pass.~
=> Test against freshly built projects on 0.59 and 0.61 on CI

cocoa/BugsnagReactNative.m
The include for `RCTVersion.h` isn't using the module form as in earlier versions of React Native (~0.53) this header was not in the `React/` scope. For users supplying their own Podfile, this means they'd need to add a separate directory to make this include work when built using Cocoapods.
* `BugsnagReactNative.m` - added conditional include of either `<React/RCTVersion.h>` or `"RCTVersion.h"` which should work on all setups.
* Confirmed via CI builds
Fixes #442
=> fix(cocoa): amend RCTVersion.h include to fix podfile use case for pre-0.60

CHANGELOG.md, index.d.ts, test/app.ts
Correct type definition of `BeforeSend`. Fixes #428.
Updated type tests to verify `BeforeSend` type definitions against expected usage.
Fixes #428.
For the submitter, initial self-review:
- This pull request is ready for:
For the pull request reviewer(s), this changeset has been reviewed for:
=> fix(types): add missing argument to BeforeSend type definition

BugsnagReactNative.podspec, CHANGELOG.md, CONTRIBUTING.md
bugsnag-cocoa v5.23.0 adds the `BugsnagPlugin.h` public header that needs to be included in bugsnag-react-native's podspec to allow `BugsnagReactNative/Bugsnag.h` to be successfully imported.
- BugsnagReactNative.podspec - reformatted public_header_files to better match bugsnag-cocoa for ease of future updates
- CONTRIBUTING.md - added note to prompt for this to be checked in future updates.
Verified locally by creating a fresh RN project, installing bugsnag-react-native and adding `#import <BugsnagReactNative/Bugsnag.h>` to a source file.
For the submitter, initial self-review:
- This pull request is ready for:
For the pull request reviewer(s), this changeset has been reviewed for:
=> Added BugsnagPlugin.h to podspec

BugsnagReactNative.podspec, CHANGELOG.md
Adds the missing comma in the public_header_files in the podspec
Manually tested following online enhanced native instructions to include required headers (`<BugsnagReactNative/BugsnagReactNative.h>` and `BugsnagConfiguration.h`).
Related to #453
=> fix(podfile): fix missing comma in headers list

.github/ISSUE_TEMPLATE/Bug_report.md, .github/SUPPORT.md
`pod -v` is now `pod --version`, updated in all docs accordingly.
Brings issue templates inline with changes made to `bugsnag-cocoa` here https://github.com/bugsnag/bugsnag-cocoa/pull/746
=> fix(pod version cmd)

examples/plain/package.json
React-native `0.59.8` has issues when attempting to run the plain example app in `Xcode 13` (see  [here](https://stackoverflow.com/questions/58051510/xcode-11-0-build-get-error-unknown-argument-type-attribute-in-method-r)).
This bumps the version to `0.59.9`, which fixes the issue.
=> Update plain example react-native version to work with Xcode 13
